# Generated by Django 4.1.1 on 2022-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
                ('epassword', models.CharField(max_length=15)),
                ('efile', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employe',
            },
        ),
    ]
